Add sqrt
cjdoris/LogarithmicNumbers.jl pull request #19
Opened 2024-01-29 13:27 UTC by mschauer

Solves #18

2024-01-31 22:18 UTC, cjdoris requested changes
Thanks for this! Could you add a test case too please - you could adapt `@testcase "pow"`.

2024-01-31 22:18 UTC, cjdoris commented on src/LogarithmicNumbers.jl
> +    uexp(x.log/2)
please change to `uexp(x.log / oftype(x.log, 2))` in order to preserve the type of `x.log`

2024-02-01 14:22 UTC, mschauer commented on src/LogarithmicNumbers.jl
> +    uexp(x.log/2)
I can change it, but division by 2 is generally typesafe

2024-02-04 16:20 UTC, merged

2024-02-04 16:20 UTC, cjdoris commented
Thanks very much!